services:
  web-app:
    build: .
    expose:
      - "8000"
    environment:
      - RUN_TYPE=docker

  nginx:
    image:
      nginx:1.27-alpine-slim
    depends_on:
      - web-app
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d